version: '3'

services:
  application:
    build: ./provisioning
    image: local-docker-laravel
    links:
      - mysql
      - phpmyadmin
    volumes:
      - "./composer:/composer"
      - ./application:/application:cached
    environment:
      PMA_HOST: mysql

  composer:
    image: composer/composer:latest
    ports:
      - "9001:9000"
    volumes:
      - "./compser:/composer"
    container_name: composer
    working_dir: /composer
    command: install

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8001:80
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      PMA_HOST: mysql

  nginx:
    image: nginx
    ports:
      - "80:8000"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./application:/application:cached
    depends_on:
      - application
